### ISSUE TITLE
Error in retrieving mobility energy demand time series

### ISSUE THREAD

**Issue by philippklughardt** [FCN-ESE/JERICHO-E-usage#1]
Dear JERICHO-E-usage team,

thank you for providing this helpful tool and data. Following error occurs when going through the second step in the Mobility sector section in the main jupyter notebook: 

The command `mobility.validate_and_scale_ts(bio_fuel_shares, benchmark_values_twh)` yields the error message: 
" AttributeError: 'ConcreteModel' object has no attribute 'FE_deviation_f' ".

See error message below:

1. Load required data sets
2. Preprocess data
3. Validate  data and calculate scaling factors
4. find optimal scaling factors
GLPSOL--GLPK LP/MIP Solver 5.0
Parameter(s) specified in the command line:
 --write /var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmpc8gw_7sg.glpk.raw
 --wglp /var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmppvt3xbjm.glpk.glp
 --cpxlp /var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmpjr8law6c.pyomo.lp
Reading problem data from '/var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmpjr8law6c.pyomo.lp'...
29 rows, 25 columns, 53 non-zeros
176 lines were read
Writing problem data to '/var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmppvt3xbjm.glpk.glp'...
132 lines were written
GLPK Simplex Optimizer 5.0
29 rows, 25 columns, 53 non-zeros
Preprocessing...
10 rows, 16 columns, 27 non-zeros
Scaling...
 A: min|aij| =  4.379e-02  max|aij| =  2.324e+02  ratio =  5.306e+03
GM: min|aij| =  5.973e-01  max|aij| =  1.674e+00  ratio =  2.803e+00
EQ: min|aij| =  3.567e-01  max|aij| =  1.000e+00  ratio =  2.803e+00
Constructing initial basis...
Size of triangular part is 10
      0: obj =  -5.856892000e+02 inf =   1.197e+03 (4)
      4: obj =   7.662222969e+01 inf =   0.000e+00 (0)
*     9: obj =   1.959854852e+00 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Time used:   0.0 secs
Memory used: 0.0 Mb (51331 bytes)
Writing basic solution to '/var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/tmpc8gw_7sg.glpk.raw'...
63 lines were written
Scaling factor of Pas is 0.900000
Scaling factor of Mot is 0.900000
Scaling factor of Tru_sm_35 is 1.447908
Scaling factor of Tru_gr_35 is 1.450000
Scaling factor of Tru_semi is 1.450000
Scaling factor of Oth is 1.450000
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/xc/46hrc1yd3t103ncpxm99t_1c0000gr/T/ipykernel_12106/1357024129.py in <module>
----> 1 mobility.validate_and_scale_ts(bio_fuel_shares, benchmark_values_twh)

~/Desktop/JERICHO-E-usage-main/src/mobility_calculate_useful_energy_ts.py in validate_and_scale_ts(bio_fuel_shares, benchmark_values_twh)
    216         scaling_factor[p] = pyomo.value(model.scaling_factor_p[p])
    217     for f in model.F:
--> 218         print("Deviation in %s is %f TWh" % (f, pyomo.value(model.FE_deviation_f[f])))
    219 
    220 

~/opt/anaconda3/envs/JERICHO-E-usage/lib/python3.9/site-packages/pyomo/core/base/block.py in __getattr__(self, val)
    519         # Since the base classes don't support getattr, we can just
    520         # throw the "normal" AttributeError
--> 521         raise AttributeError("'%s' object has no attribute '%s'"
    522                              % (self.__class__.__name__, val))
    523 

AttributeError: 'ConcreteModel' object has no attribute 'FE_deviation_f'

Your help with this would be very much appreciated.

Best regards,
Philipp

**Comment by j-priesmann** [comment]
Hi Philipp,

so sorry for the late reply. The problem should be fixed now.

Best regards,

Jan
